[tool.poetry]
name = "hpc-scheduler"
version = "0.0.1"
description = ""
authors = ["Danny de Bree"]
readme = "README.md"
packages = [{include = "poetry_demo"}]

[tool.poetry.dependencies]
python = "^3.7"
